export const COL = {
  Users: 'Users',
  Colleges: 'Colleges',
  Requests: 'Request',
  AdminUsers: 'Admin Users',
  Posts: 'Posts',
  ChallengeInfo: 'Challenge Info',
  ChallengeTopPerformer: 'Challenge Top Performer',
  PostComments: 'Post Comments',
  Followers: 'Followers',
  CommentThreads: '',
  Likes: 'Post Likes',
  FollowRequests: 'Follow Requests',
  PostCounts: 'Post Counts',
  PostLikes: 'Post Likes',
};
